### ISSUE TITLE
Create first specs and project layout

### ISSUE THREAD

**Issue by wolfhund** [amauryprieto/bazaar#1]

**Comment by wolfhund** [comment]
@amauryprieto I'm currently have this structure from an existing project layout, but I think we don't need all of it. Which of these directories are we going to keep?, also, what specs does the project has? Thanks in advance.

```
├── LICENSE.md
├── Makefile
├── README.md
├── api
│   └── README.md
├── assets
│   └── README.md
├── build
│   ├── README.md
│   ├── ci
│   └── package
├── cmd
│   ├── README.md
│   └── _your_app_
├── configs
│   └── README.md
├── deployments
│   └── README.md
├── docs
│   └── README.md
├── examples
│   └── README.md
├── githooks
│   └── README.md
├── init
│   └── README.md
├── internal
│   ├── README.md
│   ├── app
│   │   └── _your_app_
│   └── pkg
│       └── _your_private_lib_
├── pkg
│   ├── README.md
│   └── _your_public_lib_
├── scripts
│   └── README.md
├── test
│   └── README.md
├── third_party
│   └── README.md
├── tools
│   └── README.md
├── vendor
│   └── README.md
└── web
    ├── README.md
    ├── app
    ├── static
    └── template
```

**Comment by amauryprieto** [comment]
@wolfhund let's keep pkg, cmd, and vendor. Would you mind to summarize what's the purpose of those folders taking into account Go In Action chapter3?

There are not specs, we will define the project between us and share it with Juan Pablo Pizarro to have alignment.

**Comment by amauryprieto** [comment]
@wolfhund we both have the task to learn what the command 'go get' works

**Comment by wolfhund** [comment]
@amauryprieto , regarding your question, from what I understand **cmd/** should contain only executable binaries, those binaries should be named as the desired applications to have. The **pkg/** directory should contain libraries that can run for external applications. The **vendor/** directory will contain source dependencies required for the project. If I'm missing something or wrong in concepts, please let me know. Thanks.

**Comment by amauryprieto** [comment]
@wolfhund /cmd is the only one that requires a review. There we are going to place the main function that defines the applications (not the binaries) the project has.

Good job!
